/*
 * GREAT WORK! — conformance vector generator
 *
 * Emits contract/test/vectors.h: the JS engine's tick-by-tick behavior frozen
 * as data, so the C implementation can be differential-tested without a JS
 * runtime in the loop. Three sections:
 *
 *   1. primitive vectors — expected outputs of the Q16.16 core (trigQ, rotQ,
 *      toPxQ, axialRoundQ, tooCloseQ) on fixed and seeded-random inputs;
 *   2. example machines — puzzle as C literals, machine as codec bytes,
 *      expected final metrics;
 *   3. per-tick digests — FNV-1a 64 over the committed sim state after every
 *      tick, so a divergence is localized to the first tick it appears.
 *
 * The digest byte stream (all integers little-endian) is NORMATIVE and must be
 * reproduced exactly by the C side (see gw_digest in the harness):
 *   u32 tick
 *   u8  status (0 running, 1 verified, 2 fault)
 *   u8  fault kind (0 none, 1 collision, 2 overconstraint, 3 grab-cycle, 4 exhaustion)
 *   u32 products, u32 areaSize, u32 atomCount
 *   per atom, array order: u32 id, i32 q, i32 r, u8 elem, u8 nbonds,
 *                          then bond ids u32 sorted ascending
 *   u32 armCount
 *   per arm, submission order:
 *     u8 angle, u8 carryRel, u8 ncarriers, per carrier (u8 armIdx, u8 grip),
 *     u8 isElbow, if ground: i32 baseQ, i32 baseR, u8 baseRot,
 *     per gripper: u8 holdKind (0 none, 1 atom, 2 tower), u32 holdId
 *                  (atom id, or the tower's arm INDEX; 0 when none)
 *
 * The machine fed to the sim is decode(encode(example.machine)) — the codec's
 * canonical form — so arm order and indices line up with what the C decoder
 * produces from the same bytes.
 */
'use strict';
const path = require('path');
const fs = require('fs');
const GW = require(path.join(__dirname, 'engine.js'));
const CODEC = require(path.join(__dirname, 'codec.js'));
const EXAMPLES = require(path.join(__dirname, 'examples.js'));
const PUZ = require(path.join(__dirname, 'gen-puzzles.js'));

const Q = GW.Q;
const FAULTS = ['none', 'collision', 'overconstraint', 'grab-cycle', 'exhaustion'];
const elemCode = PUZ.elemCode;   // one element roster for the catalog and the vectors

// ---- FNV-1a 64 over a byte feed ----
const FNV_OFFSET = 0xcbf29ce484222325n, FNV_PRIME = 0x100000001b3n, MASK64 = 0xffffffffffffffffn;
function mkDigest() {
  let h = FNV_OFFSET;
  const u8 = (b) => { h = ((h ^ BigInt(b & 0xff)) * FNV_PRIME) & MASK64; };
  const u32 = (v) => { v = v >>> 0; u8(v); u8(v >>> 8); u8(v >>> 16); u8(v >>> 24); };
  const i32 = (v) => u32(v < 0 ? v + 0x100000000 : v);
  return { u8, u32, i32, value: () => h };
}

function digestState(S, armIndex) {
  const d = mkDigest();
  d.u32(S.tick);
  d.u8(S.fault ? 2 : S.cycles !== null ? 1 : 0);
  d.u8(S.fault ? FAULTS.indexOf(S.fault.kind) : 0);
  d.u32(S.products);
  d.u32(S.area.size);
  d.u32(S.atoms.length);
  for (const a of S.atoms) {
    d.u32(a.id); d.i32(a.cell[0]); d.i32(a.cell[1]); d.u8(elemCode(a.elem));
    const bonds = [...a.bonds].sort((x, y) => x - y);
    d.u8(bonds.length);
    for (const b of bonds) d.u32(b);
  }
  d.u32(S.arms.length);
  for (const arm of S.arms) {
    d.u8(arm.angle); d.u8(arm.carryRel); d.u8(arm.carriers.length);
    for (const c of arm.carriers) { d.u8(armIndex.get(c.arm.id)); d.u8(c.grip); }
    d.u8(arm.mount.elbow ? 1 : 0);
    if (!arm.mount.elbow) { d.i32(arm.basePos[0]); d.i32(arm.basePos[1]); d.u8(arm.baseRot); }
    for (const h of arm.holds) {
      if (!h) { d.u8(0); d.u32(0); }
      else if (h.kind === 'atom') { d.u8(1); d.u32(h.id); }
      else { d.u8(2); d.u32(armIndex.get(h.id)); }
    }
  }
  return d.value();
}

// ---- deterministic PRNG for primitive sample points ----
let seed = 0x2545f491n;
function rnd() { // xorshift64*, top 32 bits
  seed ^= (seed << 13n) & MASK64; seed ^= seed >> 7n; seed ^= (seed << 17n) & MASK64;
  return Number((seed >> 32n) & 0xffffffffn);
}
const rint = (lo, hi) => lo + rnd() % (hi - lo + 1);

// ---- emit helpers ----
const out = [];
const emit = (s) => out.push(s);
const cell = (c) => `{${c[0]},${c[1]}}`;

emit('/* GENERATED by engine/gen-vectors.js — do not edit. Regenerate after any engine change. */');
emit('#ifndef GW_VECTORS_H');
emit('#define GW_VECTORS_H');
emit('#include <stdint.h>');
emit('#include "../gw.h"');
emit('');

// ---- section 1: primitives ----
{
  const rows = [];
  for (let u = -12; u < 84; u++) { const t = Q.trigQ(u); rows.push(`{${u},${t[0]},${t[1]}}`); }
  emit(`static const struct { int32_t u; int64_t c, s; } VEC_TRIG[] = {\n  ${rows.join(', ')}\n};`);

  const rot = [];
  for (let i = 0; i < 96; i++) {
    const dx = rint(-500000, 500000), dy = rint(-500000, 500000), u = rint(-100, 200);
    const r = Q.rotQ(dx, dy, u);
    rot.push(`{${dx},${dy},${u},${r[0]},${r[1]}}`);
  }
  emit(`static const struct { int64_t dx, dy; int32_t u; int64_t ex, ey; } VEC_ROT[] = {\n  ${rot.join(',\n  ')}\n};`);

  const px = [];
  for (let q = -8; q <= 8; q++) for (let r = -8; r <= 8; r++) {
    const p = Q.toPxQ(q, r);
    px.push(`{${q},${r},${p[0]},${p[1]}}`);
  }
  emit(`static const struct { int32_t q, r; int64_t x, y; } VEC_TOPX[] = {\n  ${px.join(', ')}\n};`);

  const ax = [];
  for (let i = 0; i < 128; i++) {
    const x = rint(-40 * 65536, 40 * 65536), y = rint(-40 * 65536, 40 * 65536);
    const c = Q.axialRoundQ(x, y);
    ax.push(`{${x},${y},${c[0]},${c[1]}}`);
  }
  emit(`static const struct { int64_t x, y; int32_t q, r; } VEC_AXIAL[] = {\n  ${ax.join(',\n  ')}\n};`);

  const tc = [];
  for (let i = 0; i < 96; i++) {
    const ax_ = rint(-300000, 300000), ay = rint(-300000, 300000);
    // bias half the points to land near the threshold circle
    let bx, by;
    if (i % 2 === 0) { bx = rint(-300000, 300000); by = rint(-300000, 300000); }
    else {
      const u = rint(0, 71), t = Q.trigQ(u);
      const rr = 79000 + rint(-2000, 2000); // |d| ≈ sqrt(THRESH2*ONE) ≈ 79457
      bx = ax_ + Q.fmul(rr, t[0]); by = ay + Q.fmul(rr, t[1]);
    }
    tc.push(`{${ax_},${ay},${bx},${by},${Q.tooCloseQ(ax_, ay, bx, by) ? 1 : 0}}`);
  }
  emit(`static const struct { int64_t ax, ay, bx, by; int32_t close; } VEC_TOOCLOSE[] = {\n  ${tc.join(',\n  ')}\n};`);
  emit('');
}

// ---- section 2 + 3: examples ----
function shapeLit(g) {
  const norm = g.cell ? { cells: [g.cell], elems: [g.elem], bonds: [] }
    : { cells: g.cells, elems: g.elems, bonds: g.bonds || [] };
  if (norm.cells.length > 16 || norm.bonds.length > 32) throw new Error('shape too big for gw_shape_t');
  return `{${norm.cells.length},{${norm.cells.map(cell).join(',')}},{${norm.elems.map(elemCode).join(',')}},` +
    `${norm.bonds.length},{${norm.bonds.map(b => `{${b[0]},${b[1]}}`).join(',') || '{0,0}'}}}`;
}
const pairFam = (list) => `{${(list || []).map(g => `{${cell(g[0])},${cell(g[1])}}`).join(',') || '{{0,0},{0,0}}'}}`;
const oneFam = (list) => `{${(list || []).map(cell).join(',') || '{0,0}'}}`;

// synthetic terminal-collision case: no example ends in a collision fault, so
// freeze one — an arm swings its held atom through a resting atom's cell.
const CASES = EXAMPLES.concat([{
  key: 'collide',
  puzzle: { inputs: [{ cell: [1, 0], elem: 'Sa' }, { cell: [0, 1], elem: 'Sa' }] },
  machine: { arms: [{ id: 'A', grippers: 1, len: 1, mount: { ground: [0, 0] }, angle: 0,
    tape: { delay: 0, ops: ['G', '+'] } }] },
  expect: { fault: 'collision' },
}, {
  // repeat markers travel through the codec symbolically; the sim must run the
  // normative expansion (G + R - R -> G + G + - -), same in C as in JS
  key: 'repeat',
  puzzle: { caps: { cycles: 24 }, inputs: [{ cell: [1, 0], elem: 'Sa' }] },
  machine: { arms: [{ id: 'A', grippers: 1, len: 1, mount: { ground: [0, 0] }, angle: 0,
    tape: { delay: 0, ops: ['G', '+', 'R', '-', 'R'] } }] },
  // the carried atom sweeps back through the respawned reagent on the wrap
  expect: { fault: 'collision' },
}]);

const exNames = [];
for (const ex of CASES) {
  const p = ex.puzzle;
  const caps = Object.assign({}, GW.DEFAULT_CAPS, p.caps || {});
  const name = ex.key;
  exNames.push(name);

  const bytes = CODEC.encodeMachine(ex.machine);
  const machine = CODEC.decodeMachine(bytes);
  const sim = GW.createSim(p, machine);
  const S = sim.state;
  const armIndex = new Map(S.arms.map((a, i) => [a.id, i]));

  const digests = [];
  let guard = caps.cycles + 2;
  while (!S.fault && S.cycles === null && guard-- > 0) {
    sim.step();
    digests.push(digestState(S, armIndex));
  }
  if (guard <= 0) throw new Error(name + ': did not terminate');
  const m = sim.metrics();
  const expected = ex.expect || {};
  if (expected.cycles !== undefined && m.cycles !== expected.cycles) throw new Error(name + ': cycles drifted');
  if (expected.fault !== undefined && (!S.fault || S.fault.kind !== expected.fault)) throw new Error(name + ': fault drifted');

  emit(`/* ---- ${name} ---- */`);
  emit(`static const uint8_t MACHINE_${name}[] = {${[...bytes].join(',')}};`);
  emit(`static const gw_puzzle_t PUZZLE_${name} = {`);
  emit(`  .ninputs = ${(p.inputs || []).length}, .inputs = {${(p.inputs || []).map(shapeLit).join(',\n    ') || '{0}'}},`);
  emit(`  .has_output = ${p.output ? 1 : 0}, .output = ${p.output ? shapeLit(p.output) : '{0}'},`);
  emit(`  .natoms = ${(p.atoms || []).length}, .atom_cells = {${(p.atoms || []).map(a => cell(a.cell)).join(',') || '{0,0}'}}, .atom_elems = {${(p.atoms || []).map(a => elemCode(a.elem)).join(',') || '0'}},`);
  emit(`  .nbonders = ${(p.bonders || []).length}, .bonders = ${pairFam(p.bonders)},`);
  emit(`  .ndebonders = ${(p.debonders || []).length}, .debonders = ${pairFam(p.debonders)},`);
  emit(`  .ncalcifiers = ${(p.calcifiers || []).length}, .calcifiers = ${oneFam(p.calcifiers)},`);
  emit(`  .nduplicators = ${(p.duplicators || []).length}, .duplicators = ${pairFam(p.duplicators)},`);
  emit(`  .nprojectors = ${(p.projectors || []).length}, .projectors = ${pairFam(p.projectors)},`);
  emit(`  .npurifiers = ${(p.purifiers || []).length}, .purifiers = {${(p.purifiers || []).map(g => `{${g.map(cell).join(',')}}`).join(',') || '{{0,0},{0,0},{0,0}}'}},`);
  emit(`  .nanimismus = ${(p.animismus || []).length}, .animismus = {${(p.animismus || []).map(g => `{${g.map(cell).join(',')}}`).join(',') || '{{0,0},{0,0},{0,0},{0,0}}'}},`);
  emit(`  .ndisposals = ${(p.disposals || []).length}, .disposals = ${oneFam(p.disposals)},`);
  emit(`  .caps = {${caps.parts},${caps.elbowDepth},${caps.tapeLen},${caps.atoms},${caps.cycles},${caps.goal}},`);
  emit(`};`);
  emit(`static const uint64_t DIGESTS_${name}[] = {\n  ${digests.map(d => '0x' + d.toString(16) + 'ULL').join(',')}\n};`);
  emit(`static const gw_expect_t EXPECT_${name} = { .ticks = ${digests.length}, .status = ${S.fault ? 2 : 1}, .fault_kind = ${S.fault ? FAULTS.indexOf(S.fault.kind) : 0},` +
    ` .fault_tick = ${S.fault ? S.fault.tick : 0}, .cost = ${m.cost}, .cycles = ${m.cycles === null ? -1 : m.cycles}, .area = ${m.area}, .sum = ${m.sum === null ? -1 : m.sum} };`);
  emit('');
}

emit(`static const gw_vector_case_t VEC_CASES[] = {`);
for (const n of exNames) {
  emit(`  { "${n}", &PUZZLE_${n}, MACHINE_${n}, sizeof(MACHINE_${n}), DIGESTS_${n}, &EXPECT_${n} },`);
}
emit(`};`);
emit('');

// ---- section 4: submissions — codec v2 machines against the on-chain puzzle
// catalog (contract/puzzles.h). Exercises gw_verify end to end: the C
// materializer must rebuild exactly the puzzle the editor's matPuzzle would,
// so each reference layout is frozen unrotated AND rotated whole-board by two
// sextants (anchors, rotations, ground mounts and angles all turned together).
// Rejections pin the verifier's own checks on top of the engine's. ----
{
  const subs = [];
  const rotLayout = (p, k) => ({
    arms: p.refArms.map(a => a.mount.elbow ? a
      : Object.assign({}, a, { mount: { ground: GW.rotK(a.mount.ground, k) }, angle: ((a.angle || 0) + k) % 6 })),
    glyphs: p.defaultLayout.glyphs.map(g => ({ type: g.type, at: GW.rotK(g.at, k), rot: (g.rot + k) % 6 })),
    inputs: p.defaultLayout.inputs.map(g => ({ ri: g.ri, at: GW.rotK(g.at, k), rot: (g.rot + k) % 6 })),
    output: { at: GW.rotK(p.defaultLayout.output.at, k), rot: (p.defaultLayout.output.rot + k) % 6 },
  });
  const settle = (sim, caps) => {
    const S = sim.state;
    let guard = caps.cycles + 2;
    while (!S.fault && S.cycles === null && guard-- > 0) sim.step();
    if (guard <= 0) throw new Error('submission did not terminate');
    const m = sim.metrics();
    return { status: S.fault ? 2 : 1, fault: S.fault ? FAULTS.indexOf(S.fault.kind) : 0,
      cost: m.cost, cycles: m.cycles === null ? -1 : m.cycles, area: m.area, sum: m.sum === null ? -1 : m.sum };
  };
  const accept = (name, p, machine) => {
    const bytes = CODEC.encodeMachine(machine);
    const decoded = CODEC.decodeMachine(bytes);
    const r = settle(GW.createSim(PUZ.materialize(p, decoded), decoded), p.caps);
    subs.push(Object.assign({ name, puzzle: p.id, bytes, err: 'GW_OK' }, r));
    return r;
  };
  const reject = (name, p, machine, err) => {
    subs.push({ name, puzzle: p.id, bytes: CODEC.encodeMachine(machine), err,
      status: 0, fault: 0, cost: 0, cycles: 0, area: 0, sum: 0 });
  };
  for (const p of PUZ.puzzles()) {
    const ex = EXAMPLES.find(e => e.key === p.key);
    const r0 = accept(`${p.key} r0`, p, rotLayout(p, 0));
    // the materialized reference must be the example itself
    const ref = settle(GW.createSim(ex.puzzle, CODEC.decodeMachine(CODEC.encodeMachine(ex.machine))), p.caps);
    for (const f of ['status', 'fault', 'cost', 'cycles', 'area', 'sum']) {
      if (r0[f] !== ref[f]) throw new Error(`${p.key}: materialized ${f} ${r0[f]} != example ${ref[f]}`);
    }
    accept(`${p.key} r2`, p, rotLayout(p, 2));
  }
  {
    const p = PUZ.puzzles()[0], lay = rotLayout(p, 0);
    reject('v1 bytes carry no layout', p, { arms: lay.arms }, 'GW_ERR_LAYOUT');
    reject('a reagent left out', p, Object.assign({}, lay, { inputs: lay.inputs.slice(1) }), 'GW_ERR_REAGENTS');
    reject('a reagent placed twice', p, Object.assign({}, lay, { inputs: [lay.inputs[0], lay.inputs[0]] }), 'GW_ERR_REAGENTS');
    reject('reagent index out of range', p, Object.assign({}, lay,
      { inputs: [lay.inputs[0], Object.assign({}, lay.inputs[1], { ri: 7 })] }), 'GW_ERR_REAGENTS');
    reject('no product glyph', p, Object.assign({}, lay, { output: undefined }), 'GW_ERR_OUTPUT');
    reject('glyph on the product', p, Object.assign({}, lay,
      { glyphs: [{ type: 'bonders', at: lay.output.at, rot: 0 }] }), 'GW_ERR_GLYPH_OVERLAP');
  }
  subs.forEach((s, i) => emit(`static const uint8_t SUBMIT_${i}[] = {${[...s.bytes].join(',')}};`));
  emit(`static const gw_submit_case_t VEC_SUBMITS[] = {`);
  subs.forEach((s, i) => emit(`  { "${s.name}", ${s.puzzle}, SUBMIT_${i}, sizeof(SUBMIT_${i}), ${s.err}, ${s.status}, ${s.fault}, ${s.cost}, ${s.cycles}, ${s.area}, ${s.sum} },`));
  emit(`};`);
  emit('');
}
emit('#endif /* GW_VECTORS_H */');

const dest = path.join(__dirname, '..', 'contract', 'test', 'vectors.h');
fs.mkdirSync(path.dirname(dest), { recursive: true });
fs.writeFileSync(dest, out.join('\n') + '\n');
console.log('wrote', dest, out.join('\n').length, 'bytes;', exNames.length, 'cases');

// the catalog the submissions were generated against
const catalog = path.join(__dirname, '..', 'contract', 'puzzles.h');
fs.writeFileSync(catalog, PUZ.header());
console.log('wrote', catalog, PUZ.puzzles().length, 'puzzles');
